// Write packages/arborium-rt/src/languages.ts from the set of grammar subdirs
// currently present under packages/arborium-rt/dist/grammars/. Called after
// each buildPackage so the constant stays in sync with what's actually been
// packaged. The generated file is gitignored and consumed by src/index.ts.

import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { paths } from './util.js';

export function writeLanguagesModule(): void {
    const p = paths();
    const langs = existsSync(p.packagesOut)
        ? readdirSync(p.packagesOut)
              .filter((name) => statSync(join(p.packagesOut, name)).isDirectory())
              .filter((name) => existsSync(join(p.packagesOut, name, 'index.js')))
              .sort()
        : [];

    const srcDir = join(p.runtimePackageDir, 'src');
    mkdirSync(srcDir, { recursive: true });
    writeFileSync(join(srcDir, 'languages.ts'), renderLanguagesTs(langs));
}

function renderLanguagesTs(langs: readonly string[]): string {
    const items = langs.map((id) => `    ${JSON.stringify(id)},`).join('\n');
    return `// AUTO-GENERATED by \`arborium-rt package\` — do not edit.
// Regenerated from the grammar subdirs currently under dist/grammars/.

/**
 * Every grammar id that ships as a subpath module under
 * \`@discord/arborium-rt/grammars/<id>\`. Useful for building language
 * pickers or validating user input before dynamically importing a grammar.
 */
export const AVAILABLE_LANGUAGES = [
${items}
] as const;

/** Union of every language id in {@link AVAILABLE_LANGUAGES}. */
export type AvailableLanguage = (typeof AVAILABLE_LANGUAGES)[number];
`;
}
